# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            James Carleton
tagline:          
description:      'UX Designer'
url:              http://carletondesign.com

author:
  name:           'James Carleton'
  url:            http://carletondesign.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/fwg001/fwg001.github.io
  
 assets:
    sources:
      - assets/fonts